cart = ["apple", "banana", "milk", "bread", "apple", "eggs"]
apple_count = cart.count("apple")
print("Number of apples:", apple_count)
milk_position = cart.index("milk")
print("Position of milk:", milk_position)
cart.remove("apple")
removed_item = cart.pop()
print("Removed item using pop:", removed_item)
print("Is banana in cart?", "banana" in cart)
print(f"Final cart:", cart)